import numpy as np

"""
This module provides functions to model and analyze a curve consisting of an exponential growth segment followed by an exponential decay segment. It includes functions to create the curve, calculate specific points on it, and evaluate probabilities based on its shape. 

Its intended use is to derive the probability of a patient being admitted to a hospital within a certain elapsed time after their arrival in the Emergency Department (ED), given the hospital's aspirations for the time it takes patients to be admitted. For this purpose, two points on the curve are required as parameters: 
(x1,y1) : The target proportion of patients y1 (eg 76%) who have been admitted or discharged by time x1 (eg 4 hours). It is assumed that values of y where x < x1 is a growth curve grow exponentially towards x1 and that (x1,y1) the curve switches to a decay curve
(x2, y2) : The time x2 by which all but a small proportion y2 of patients have been admitted. 

The curve is generated by the following functions:

- growth_curve: Calculate exponential growth at a point where x < x1.
- decay_curve: Calculate exponential decay at a point where x >= x1.
- create_curve: Generate a full curve with both growth and decay segments.

The curve is applied as follows
- get_y_from_aspirational_curve: Read from the curve a value for y, the probability of being admitted, for a given moment x hours after arrival
- calculate_probability: Compute the probability of a patient being admitted by the end of a time window, given how much time has elapsed since their arrival.

"""


def growth_curve(x, a, gamma):
    """
    Calculate the exponential growth value at a given x using specified parameters.

    Parameters
    ----------
    x : float
        The x-value at which to evaluate the curve.
    a : float
        The coefficient that defines the starting point of the growth curve when x is 0.
    gamma : float
        The growth rate coefficient of the curve.

    Returns
    -------
    float
        The y-value of the growth curve at x.
    """
    return a * (np.exp(x * gamma))


def decay_curve(x, x1, y1, lamda):
    """
    Calculate the exponential decay value at a given x using specified parameters.

    Parameters
    ----------
    x : float
        The x-value at which to evaluate the curve.
    x1 : float
        The x-value where the growth curve transitions to the decay curve.
    y1 : float
        The y-value at the transition point, where the decay curve starts.
    lamda : float
        The decay rate coefficient.

    Returns
    -------
    float
        The y-value of the decay curve at x.
    """
    return y1 + (1 - y1) * (1 - np.exp(-lamda * (x - x1)))


def create_curve(x1, y1, x2, y2, a=0.01):
    """
    Generates a continuous curve composed of an exponential growth segment followed by an exponential decay segment, using specified transition points and coefficients.

    Parameters
    ----------
    x1 : float
        The x-value where the curve transitions from growth to decay.
    y1 : float
        The y-value at the transition point x1.
    x2 : float
        The x-value defining the end of the decay curve for calculation purposes.
    y2 : float
        The y-value at x2, intended to fine-tune the decay rate.
    a : float, optional
        The initial value coefficient for the growth curve, defaults to 0.01.

    Returns
    -------
    tuple
        Contains the growth rate (gamma), decay rate (lamda), initial value coefficient (a), array of x-values, and corresponding array of y-values.
    """

    # Validate inputs
    if not (x1 < x2):
        raise ValueError("x1 must be less than x2")
    if not (0 < y1 < y2 < 1):
        raise ValueError("y1 must be less than y2, and both must be between 0 and 1")

    # Constants for growth
    gamma = np.log(y1 / a) / x1

    # Constants for decay
    x_delta = x2 - x1
    lamda = np.log((1 - y1) / (1 - y2)) / x_delta

    # Generate x values
    x_values = np.linspace(0, 20, 200)

    # Compute y values for each x
    y_values = [
        growth_curve(x, a, gamma) if x <= x1 else decay_curve(x, x1, y1, lamda)
        for x in x_values
    ]
    return gamma, lamda, a, x_values, y_values


def get_y_from_aspirational_curve(x, x1, y1, x2, y2):
    """
    Calculate the probability y that a patient will have been admitted by a specified x after their arrival, by reading from the aspirational curve that has been constrained to pass through points (x1, y1) and (x2, y2) with an exponential growth curve where x < x1 and an exponential decay where x < x2

    Parameters
    ----------
    x : float
        The x-coordinate at which to calculate the y-value on the curve.
    (x1,y1) :
        The target proportion of patients y1 (eg 76%) who have been admitted or discharged by time x1 (eg 4 hours).
    (x2, y2) :
        The time x2 by which all but a small proportion y2 of patients have been admitted.

    Returns
    -------
    float
        The calculated y-value (probability of admission) at the given x, based on the combined growth and decay curve parameters.

    """

    gamma, lamda, a, x_values, y_values = create_curve(x1, y1, x2, y2)

    if x < x1:
        return growth_curve(x, a, gamma)
    else:
        return decay_curve(x, x1, y1, lamda)


def calculate_probability(elapsed_los_td_hrs, time_window_hrs, x1, y1, x2, y2):
    """
    Calculates the probability of an admission occurring within a specified time window after the moment of prediction, based on the patient's elapsed time in the ED prior to the moment of prediction and the length of the window

    Parameters
    ----------
    elapsed_los_td_hrs : float
        The elapsed time since the patient arrived at the ED.
    time_window_hrs : float
        The duration of the time window after the point of prediction, for which the probability is calculated.
    (x1,y1) :
        An aspirational target, expressed in the form of a point on a curve, representing a proportion of patients y1 (eg 76%) who - if the ED meets its targets - will be admitted or discharged by time x1 (eg 4 hours).
    (x2,y2) :
        An aspirational target, expressed in the form of a point on a curve, representing a time x2 by which all but a small proportion y2 of patients have been admitted if the ED meets its targets.

    Returns
    -------
    float
        The probability of the event occurring within the given time window.

    Edge Case Handling
    ------------------
    When elapsed_los_td_hrs is extremely high, such as values significantly greater than x2, the admission probability prior to the current time (`prob_admission_prior_to_now`) can reach 1.0 despite the curve being asymptotic. This scenario can cause computational errors when calculating the conditional probability, as it involves a division by zero. In such cases, this function directly returns a probability of 1.0, reflecting certainty of admission.

    Example
    -------
    Calculate the probability that a patient, who has already been in the ED for 3 hours, will be admitted in the next 2 hours. The ED targets that 76% of patients are admitted or discharged within 4 hours, and 99% within 12 hours.

    >>> calculate_probability(3, 2, 4, 0.76, 12, 0.99)
    """
    # probability of still being in the ED now (a function of elapsed time since arrival)
    prob_admission_prior_to_now = get_y_from_aspirational_curve(
        elapsed_los_td_hrs, x1, y1, x2, y2
    )

    # prob admission when adding the time window added to elapsed time since arrival
    prob_admission_by_end_of_window = get_y_from_aspirational_curve(
        elapsed_los_td_hrs + time_window_hrs, x1, y1, x2, y2
    )

    # Direct return for edge cases where `prob_admission_prior_to_now` reaches 1.0
    if prob_admission_prior_to_now == 1:
        return 1.0

    # Calculate conditional probability within the time window
    return (prob_admission_by_end_of_window - prob_admission_prior_to_now) / (
        1 - prob_admission_prior_to_now
    )
